-- phpMyAdmin SQL Dump
-- version 3.3.7deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 08, 2012 at 01:16 PM
-- Server version: 5.1.49
-- PHP Version: 5.3.3-1ubuntu9

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `household_syp`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8_unicode_ci,
  `regular_price` float DEFAULT NULL,
  `target_price` float DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `quantity` int(11) DEFAULT NULL,
  `is_live` tinyint(1) DEFAULT '1',
  `category` smallint(6) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=11 ;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `user_id`, `name`, `description`, `regular_price`, `target_price`, `created_at`, `updated_at`, `image`, `quantity`, `is_live`, `category`) VALUES
(1, 1, 'GE 18.1 cu. ft. Top Freezer Refrigerator in White', 'Want it delivered to your home? Search Internet #203547879. GE Profile products offer the best in contemporary design matched with the latest in appliance technology to transform the way you live. Energy Star qualified appliances feature a bold, dramatic look and state of the art features. This collection provides the perfect combination of style and innovation throughout your kitchen.\r\n\r\n\r\nWant it delivered to your home? Search Internet #203547879\r\nClick here to learn more about GE Appliances\r\nAdjustable spill-resistant glass shelves - Shelves are designed to keep spills from creating bigger messes\r\nClear crisper drawers - Transparent drawers make finding your favorite snacks quick and easy\r\nSnack drawer - Conveniently stores favorite foods and allows for quick, easy access\r\nGallon door storage - Milk and larger items are easily accommodated in the door\r\nCan storage door shelf - Holds soft drink cans in the door for easy selection and quick access\r\nWire freezer shelf - A sturdy shelf provides additional storage for frozen foods\r\nNeverclean condenser - Sealed compartment keeps coils clean and simplifies maintenance\r\nFresh food cabinet shelves 2 total - glass, 2 adjustable, 2 full-width, spill-resistant\r\nFresh food door shelves 3 fixed (2 with Gal. Storage)\r\nFresh food cabinet drawers 3 total clear, 1 snack drawer, 2 adjustable humidity crispers\r\nLeveling system 2 point front adjustable\r\nEco Options : Eco Options\r\nMFG Brand Name : GE\r\nMFG Model # : GTH18GBDWW\r\nMFG Part # : GTH18GBDWW', 599, 419, '2012-08-08 07:27:40', '2012-08-08 07:27:40', 'e58b155e-b486-46f5-98b6-4312b0da97f7_300.jpg', NULL, 1, 0),
(2, 1, 'Maytag 20.6 cu. ft. Top Freezer Refrigerator in Black', 'Combine efficiency and capacity in a top-freezer refrigerator. This ENERGY STAR qualified refrigerator helps you save money on utility bills. The convenient ice maker produces fresh ice in the freezer, eliminating the need to refill ice cube trays. Plus, it''s installed at the factory, so there''s no need to purchase a kit. A full-width Spill-Catcher glass shelf provides plenty of room for extra-wide items, while the FreshLock humidity controlled crispers help preserve the freshness of vegetables and fruit.\r\n\r\n\r\nCLICK HERE to learn more about Maytag Appliances\r\nENERGY STAR qualified and CEE Tier I rated, to help you save money on utility bills, use less energy and help preserve our natural resources\r\nFactory-installed icemaker eliminates the need to fill ice trays and helps you have a steady supply of ice on hand\r\nTemperature control is located at the top of the refrigerator compartment. A single knob controls the temperature in both the refrigerator and freezer compartments\r\nCool Flow ventilation: vents in the fresh food and freezer compartments circulate cold air around large items\r\nAdjustable Spill-Catcher glass shelves help contain spills for quick and easy cleanup\r\nFreshLock humidity controlled crispers help preserve the freshness of fruits and vegetables\r\nAdjustable gallon-sized refrigerator compartment door bins for flexible loading and quick cleaning\r\n14.4 cu. ft. fresh food compartment and 6.2 cu. ft. freezer compartment provide spacious storage options\r\nFull-width freezer shelf and 2 freezer door shelves help keep your freezer organized\r\nReversible door can open from the left or the right to fit into most kitchen spaces\r\nRefrigerator compartment''s incandescent lighting makes finding items easy\r\nEco Options : Eco Options\r\nMFG Brand Name : Maytag\r\nMFG Model # : M1TXEGMYB\r\nMFG Part # : M1TXEGMYB', 764, 535, '2012-08-08 07:31:36', '2012-08-08 07:31:36', '5dd0db9d-c01f-4ad0-9f1e-00c15bf67319_300.jpg', NULL, 1, 0),
(3, 1, 'Summit Appliance 10.18 cu. ft. Top Freezer Refrigerator in Stainless Steel', 'SUMMIT offers frost-free refrigerator-freezers with slim dimensions for smaller kitchens and superior construction for years of reliable service. The FF1325SS has one of the largest interior capacities in the industry to fit into a 24 in. footprint. Adjustable glass shelves and full door racks in both compartments provide users with plenty of storage options to accommodate all sorts of items. The deluxe interior includes an extra-large freezer, interior lighting, and crisper. Frost-free operation guarantees quality cooling with minimum maintenance. Energy efficient and fully featured, the FF1325SS has a platinum cabinet and a fingerprint-proof stainless steel door. Its modern style makes this unit an elegant addition to any home kitchen with limited space but high standards.\r\n\r\n\r\nExtremely narrow width fits into even the tightest spaces\r\nStainless steel door brings modern style into the kitchen\r\nLarge capacity meets all your storage needs\r\nFull frost-free operation saves you maintenance\r\nAdjustable glass shelves offer flexible storage solutions\r\nCrisper drawer with humidity controls is ideal for preserving greens\r\nDoor racks offer convenient storage for cans and condiments\r\nReversible doors provide flexible placement options\r\nInterior light automatically illuminates when the door is opened\r\nLarge freezer section includes two door shelves\r\n**This product is excluded from Major Appliance Free Delivery and Haul Away promotion**\r\nMFG Brand Name : Summit Appliance\r\nMFG Model # : FF1325SS\r\nMFG Part # : FF1325SS', 829, 580, '2012-08-08 07:32:38', '2012-08-08 07:32:38', 'b3726960-47d8-4bfb-84df-01507d2e9257_300.jpg', NULL, 1, 1),
(4, 1, 'Hampton Bay Glendale 52 in. Oil Rubbed Bronze Ceiling Fan', 'The Hampton Bay Glendale 52 in. Ceiling Fan features an oil-rubbed bronze finish and 5 reversible dark teak/walnut blades for a handsome transitional look that complements a variety of home decor. The 3-light kit comes with light amber glass and uses three 13-watt CFL bulbs, included. The fan offers 3-speed reversible control so you can easily control the speed and airflow, and the multi-capacitor provides quiet operation.\r\n\r\n\r\n5 reversible dark teak/walnut blades allow you to change your decor style without replacing the entire unit\r\n3-light kit with light amber glass\r\n3-speed reversible control\r\nOil-rubbed bronze finish for a transitional style\r\nDesigned for interior use\r\nUses three 13-watt CFL bulbs, included\r\nMulti-capacitor offers quiet operation\r\nUp to 5,450 CFM airflow\r\nLarge room: room size up to 20 ft. x 20 ft.\r\nUL listed\r\nMFG Brand Name : Hampton Bay\r\nMFG Model # : AG524-ORB\r\nMFG Part # : AG524-ORB', 70, 49, '2012-08-08 07:34:23', '2012-08-08 07:34:23', '9ee836b1-c5bc-43fa-9403-4643d54da6a1_300.jpg', NULL, 1, 1),
(5, 1, 'Hunter Fairhaven 52 in. Ceiling Fan - Antique Pewter with Remote Control Included', 'Hunter is the oldest branded ceiling fans made dating back to 1886. The Fairhaven Ceiling fan is a high end styled fan at a very affordable price. This product is available in 3 finishes including Basque Black, Antique Pewter, and Brushed Nickel.\r\n\r\n\r\nCarved blades\r\nRemote control included: CFL compatible, full dimming, 3 speed fan control\r\nDesigner style and finishes\r\n3 60w candelabra light kit included\r\nLimited lifetime warranty\r\nFrosted white glass bowl\r\nBushed nickel finish\r\nMFG Brand Name : Hunter\r\nMFG Model # : 22549\r\nMFG Part # : 22549\r\nSavings Center : Special Buys', 129, 90, '2012-08-08 07:35:23', '2012-08-08 07:35:23', '01ba4e87-219f-445d-b10e-02b3fb8b5b5f_300.jpg', NULL, 1, 1),
(6, 1, 'Hampton Bay Littleton 42 in. Ceiling Fan', 'The Littleton 42 in. Ceiling Fan features a white finish with 4 reversible white/bleached oak blades and a schoolhouse light kit with a frosted-glass globe shade for a transitional look that complements a variety of decor styles. The fan is ideal for use in rooms up to 10 ft. x 10 ft. in size and offers 3-speed reversible operation to help you easily select the desired speed and direction.\r\n\r\n\r\n4 reversible white/bleached oak blades make it easy to change your decor style without replacing the entire unit\r\nSingle-light schoolhouse light kit with frosted glass\r\n3-speed reversible operation\r\nWhite finish complements a variety of decor styles\r\nDesigned for interior use\r\nUses one 13-watt CFL bulb, included\r\nUp to 3,600 CFM airflow\r\nFor small room sizes up to 10 ft. x 10 ft.\r\nFlush-mount installation\r\nLight kit is not optional\r\nUL listed\r\nMFG Brand Name : Hampton Bay\r\nMFG Model # : UB42S-WH-SH\r\nMFG Part # : UB42S-WH-SH', 26, 18, '2012-08-08 07:36:36', '2012-08-08 07:36:36', 'c14b19b8-37d1-429d-9cf7-ce78058b1edf_300.jpg', NULL, 1, 0),
(7, 1, 'LG Electronics 3.6 cu. ft. High Efficiency Front Load Steam Washer in Graphite Steel', 'The LG Electronics 3.6 cu. ft. (DOE) Front Load Steam Washer features 9 wash programs, including delicates, cotton/normal, hand wash/wool and Speed Wash, for worry-free fabric care. The electronic control panel on the washer has an easy-to-read LED display and Dial-A-Cycle to make it easy to find the right setting. The washer''s Allergiene cycle helps reduce more than 95% of common household allergens, such as dust mites and domestic animal dander. This washer is Energy Star qualified for year-round energy and money savings.\r\n\r\n\r\nThe extra large 3.6 cu. ft. (DOE) capacity means fewer loads, saving time and energy, plus the extra large door opening makes it easy to load and unload your laundry\r\nElectronic control panel with LED display - Intuitive Dial-A-Cycle controls and easy to read LED display indicators help you find the right setting every time for you laundry needs\r\nColdWash technology uses cold water and enhanced washing motions to deliver cold-water savings with a warm-water performance\r\nGet your clothes cleaner and give them a longer life with revolutionary 6Motion technology, combines up to 6 different wash motions to work harder than ever to knock out dirt without being hard on fabrics\r\n9 wash programs: Allergiene, sanitary, bulky/large, cotton/normal, perm press, delicates, hand wash/wool, speed wash, tub clean, match loads for worry free and optimal fabric care\r\nLG Washers are Energy Star qualified and meet Consortium for Energy Efficiency Standards for a Tier III Rating, doing their important part for the environment\r\nThe NeveRust stainless steel drum resists rust and offers durability\r\nSteam deeply penetrates fabrics to knock out dirt and reduce wrinkles and odors while it also uses less water than traditional washers, so you won''t take a bath on your bills\r\nThe Allergiene cycle uses the power of steam to gently remove over 95% of common household allergens, like dust mites and pet dander, from even the most delicate fabrics\r\nTrueBalance anti-vibration system is designed to minimize washer vibration for smooth, quiet performance in any room of the house - even on the 2nd floor\r\nThe SenseClean wash system sets the water and washes time automatically based on the weight and size of each load for optimal washing care\r\nThe SpeedWash Cycle can have clothes clean and fresh quickly, when you just do not have time to wait\r\nMFG Brand Name : LG Electronics\r\nMFG Model # : WM2655HVA\r\nMFG Part # : WM2655HVA', 899, 629, '2012-08-08 07:39:13', '2012-08-08 07:39:13', 'cb49ca21-6218-4744-a5cb-66fecae32f59_300.jpg', NULL, 1, 0),
(8, 1, 'GE 4.1 cu. ft. DOE High-Efficiency Front Load Washer in White', 'The GE 4.1 cu. ft. Front Load Washer uses reversing tumble wash action to gently lift then drop clothes into the wash water solution, helping you achieve a thorough cleansing with less wear on fabrics. This Energy Star qualified washer has an eWash option that uses a cold water wash on select cycles to help deliver great washing action without sacrificing performance. The washer''s HydroHeater internal water heater boosts incoming water temperatures to help brighten whites while helping eliminate common bacteria.\r\n\r\n\r\nCLICK HERE to learn more about GE Washers\r\n4.1 cu. ft. washer handles large loads to help you spend less time in the laundry room\r\nReversing tumble wash action gently lifts then drops the load into the wash water solution for thorough cleansing with less wear on fabrics\r\nHydroheater internal water heater boosts incoming water temperatures to help brighten whites while helping eliminate common bacteria\r\n1,200 rpm spin speed helps remove water efficiently to minimize dry time\r\n11 wash cycles, including heavy-duty, hand washable and delicates cycles, help you care properly for a wide range of fabrics\r\nStain Wash cycle is designed to fight tough stains and provide a deep, thorough clean\r\nSpeed Wash Cycle delivers a quick wash for lightly soiled items that are needed in a hurry\r\nRinse-and-spin cycle offers a fast, convenient way to remove odors and residue from items like swimsuits and towels\r\neWash option uses a cold water wash on select cycles without sacrificing performance\r\nEnergy star qualified to meet or exceed federal guidelines for energy efficiency for year-round energy and money savings\r\nStainless steel tub is durable\r\nEco Options : Eco Options\r\nMFG Brand Name : GE\r\nMFG Model # : GFWH2400LWW\r\nMFG Part # : GFWH2400LWW', 809, 566, '2012-08-08 07:40:04', '2012-08-08 07:40:04', 'e6180ccd-3125-48a0-bf63-36c53af4ba17_300.jpg', NULL, 1, 0),
(9, 1, 'LG Electronics 5.1 cu. ft. Capacity High Efficiency Front Load SteamWasher with TurboWash Wash in White', 'Imagine being able to wash a king size comforter and a full set of bedding in a single load. And just think how much more amazing this would be if you could tackle a regular load of laundry 20 minutes faster. Stop imagining and go for it. LG takes the industry''s largest capacity washer and powers it to the max with time-saving TurboWash technology and a steam cleaning feature that virtually eliminates dirt, wrinkles and odors.\r\n\r\n\r\nCLICK HERE to learn more about LG Appliances\r\nThe largest capacity washer available at 5.1 cu ft, you can fit a comforter and full set of king size bedding in a single load\r\nElectronic control panel with Dual LED Display and Dial-A-Cycle makes selecting the right easy\r\nLG''s revolutionary TurboWash technology allows you to wash larger loads 20 minutes faster, with outstanding cleaning performance\r\nAwarded the 2012 EnergyStar most efficient designation\r\nGet your clothes cleaner and give them a longer life with revolutionary 6Motion technology, 6 different wash motions work harder than ever to knock out direct without being hard on fabrics\r\n14 Wash Cycles, including AAFA- Certified Allergiene, NSF-certified Sanitary and Hand Wash/Wool\r\nColdWash technology uses cold water and enhanced washing motions to deliver cold-water saving with a warm-water performance\r\nThe NeveRust stainless steel drum resists rust and offers durability\r\nSteam technology deeply penetrates fabrics to know out dirt and reduce wrinkles and odors while it also uses less water than traditional washers, so you won''t take a bath on your bills\r\nAllergiene cycle helps remove more than 95% of common household allergens, including dust mites and pet dander, helping to improve clothing hygiene\r\nTrueBalance Anti-Vibration System is designed to minimize washer vibration for smooth, quiet performance in any room of the house - even on the 2nd floor\r\nThe sense clean wash system sets the water and wash time automatically based on the weight and size of each load for optimal washing care\r\nMFG Brand Name : LG Electronics\r\nMFG Model # : WM8000HWA\r\nMFG Part # : WM8000HWA', 1399, 979, '2012-08-08 07:41:12', '2012-08-08 07:41:12', 'b25d0920-ae62-4bb0-b200-85a1ee95bde4_300.jpg', NULL, 1, 1),
(10, 1, 'Maytag Maxima 4.3 cu. ft. High-Efficiency Front Load Washer in Granite', 'From America''s #1 preferred laundry brand comes a premium laundry experience equipped with the PowerWash cycle for the best cleaning in the industry. To keep your household''s clothes, fabrics and special items ready for daily life, this high-efficiency 4.3 cu. ft. washer includes a 10-year limited parts warranty and Maytag Commercial Technology. The 16-hour Fresh Hold option keeps clothes left in the washer fresh. With a CEE Tier III rating this model help to reduce utility bills and its NSF Certified Sanitize setting removes 99.9% of household bacteria. Why do we put so much thought into your laundry? So you don''t have to.\r\n\r\n\r\nCLICK HERE to learn more about Maytag Appliances\r\n4.3 cu. ft. capacity easily handles large loads and bulky items such as comforters\r\nFront panel controls provide convenient access to all cycle and option selections\r\n11 automatic cycles include Power Wash, Whites, Heavy Duty, Normal, Wrinkle Control, Allergen and Delicate to provide washing options to handle a large variety of fabrics and soil levels\r\nENERGY STAR qualified with a CEE Tier III rating: this washer is among the most efficient washers in the industry\r\nCommercial-grade, stainless steel wash basket resists odors, rust and chipping and the smooth surface helps protect delicate fabrics from snagging\r\nIntelliTemp automatic temperature control monitors incoming water for correct temperature; The washer begins filling after the optimal temperature has been reached\r\nIntelliFill automatic water level sensors detect the load size and automatically adjust water usage, which helps save resources\r\nDelay Wash option allows you to set the washer to begin cleaning up to 8 hours later, during off-peak hours when utility rates may be lower, or when unloading the washer may be more convenient\r\nQuietSeries sound package: sound-dampening materials are added to the interior of the washer to reduce noise for quieter operation and less household disruption\r\n16 hour Fresh Hold with Dynamic Venting technology circulates air in the washer to help keep clean laundry smelling fresh and help keep wrinkles from setting in for up to 16 hours after the wash cycle ends\r\nPowerWash cycle provides the best cleaning in the industry with extra cleaning action and a thorough rinse\r\nStackable design allows the coordinating dryer to be stacked on top of the washer for increased installation options, stacking kit (model W10298318RP) sold separately\r\nEco Options : Eco Options\r\nMFG Brand Name : Maytag\r\nMFG Model # : MHW6000XG\r\nMFG Part # : MHW6000XG\r\nSavings Center : Special Buys', 1299, 909, '2012-08-08 07:42:10', '2012-08-08 07:42:10', '4534d1c5-1a9b-4447-8eca-524213f9ba23_300.jpg', NULL, 1, 1);
